### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [antontimmermans/MOMPOS#1]
Do I need to write anything more?

**Comment by antontimmermans** [comment]
Nope...As usual, I prepared a translation slide.
I have tried to simplify the translation by reducing duplicated text, The Old journal text is quite large. Thank you for doing this.

https://docs.google.com/spreadsheets/d/1FhOLeD1WkKHWen6cYfV5-fOEW125rnc4ft1USNiobMs/edit#gid=278224675

**Comment by vidimus** [comment]
OK, I will wait until you get some feedback in case you want to change something. I already left you some.

**Comment by antontimmermans** [comment]
Spanish translation integrated, feedback is looking good.
Closing this issue
