### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by LabBrab** [antontimmermans/MOMPOS#3]
Hi Anton,

I translated your next scenario - Possessed into Czech language. I am attaching the file. I'll be happy if you add him to Valkyrie soon.

Best regards

LabBrab

[Localization.Czech.txt](https://github.com/antontimmermans/MOMPOS/files/10854383/Localization.Czech.txt)

**Comment by LabBrab** [comment]
Hi Anton

Please can you add this Czech translation to your scenario? :)

**Comment by antontimmermans** [comment]
Hey LabBrab, 
my sincere appologies for not noticing this before. It will be released in ~1 hr.

One question though. This scenario has English voiceover during introduction and epilogue. Unfortunaltely, I don't have those in Czech. Would you prefer to hear the English voiceover or no voicevoice? I assume you want with English voiceover, but i'll remove it if you say the word.

Best regards,
Anton

**Comment by LabBrab** [comment]
Hey Anton,

I wouldn't add a voiceover to the scenario. Thanks

**Comment by antontimmermans** [comment]
OK, I removed the voiceover. Thank you for the feedback and the translation.
i will close this ticket now
